name: toplearth
description: "toplearth is a plogging app that helps you to clean up the earth."

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  # Default
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Collection
  collection: ^1.18.0

  # Icons
  cupertino_icons: ^1.0.6

  # Social Share
  social_share: ^2.3.1

  # Localization
  intl: ^0.19.0
  timezone: ^0.9.4

  # Logger
  logger: ^2.4.0

  # GetX
  get: ^4.6.6

  # Svg
  flutter_svg: ^2.0.10+1

  # Shimmer
  shimmer: ^3.0.0

  # Cached Network Image
  cached_network_image: ^3.4.1
  cached_memory_image: ^1.5.0

  # Extended Nested Scroll View
  extended_nested_scroll_view: ^6.2.1

  # debounce_throttle
  debounce_throttle: ^2.0.0

  # model_viewer_plus
  model_viewer_plus: ^1.9.0

  # Storage
  get_storage: ^2.1.1
  flutter_secure_storage: ^9.2.2

  # Environment Encrypted
  envied: ^0.5.4+1

  # Percent Indicator
  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^24.1.45

  # Permission And Health
  permission_handler: ^11.2.1
  health: ^9.0.1

  # Custom Time Chart
  path_drawing: ^1.0.1
  touchable: ^1.0.2
  linked_scroll_controller: ^0.2.0

  # Kakao Login
  kakao_flutter_sdk: ^1.9.6
  kakao_flutter_sdk_user: ^1.9.6
  kakao_flutter_sdk_share: ^1.9.6

  # Apple Login
  sign_in_with_apple: ^6.1.3

  # Animation
  rive: ^0.13.15
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^1.1.0

  # ft_chart
  fl_chart: ^0.66.0
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_local_notifications: ^18.0.1
  flutter_naver_map: ^1.3.0+1
  url_launcher: ^6.3.1


  image_picker: ^1.1.2

  # stomp
  stomp_dart_client: ^1.0.3

  path_provider: ^2.1.5
  googleapis_auth: ^1.6.0

  # geolocation
  geocoding: ^3.0.0
  geolocator: ^13.0.2

dev_dependencies:
  # Default
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Localization
  intl_translation: ^0.20.0

  # App Package Name Change
  change_app_package_name: ^1.4.0

  # App Icon
  flutter_launcher_icons: ^0.13.1

  # Environment Encrypted
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/shares/
    - assets/images/seoul/
    - assets/icons/
    - assets/icons/bottom_navigation/
    - assets/animations/
    - assets/config/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon_ios.png"
